### ISSUE TITLE
City & Timezone Request

### ISSUE THREAD

**Issue by pije76** [yunojuno/django-geoip2-extras#1]
It would be nice if can get city & timezone too

**Comment by hugorodgerbrown** [comment]
Happy to accept pull requests for this :-)

The one thing to be aware of is that the city database is 10x the size of the country database, so any changes to the middleware would have have to handle the various combinations of database (inc. none).

1. City database exists:
    add city, country, tz info
2. Country database exists:
    add country info
3. No database exists:
    disable middleware

Cases 2,3 already exist.

**Comment by hugorodgerbrown** [comment]
See #2

**Comment by pije76** [comment]
Great! Thanks for this.
Keep it good work ! (y)
