### ISSUE TITLE
Easy testing in local dev env

### ISSUE THREAD

**Issue by maltebeckmann** [yunojuno/django-geoip2-extras#10]
Hi! 

Nice and easy to use library! 

Is there any way to test in a local dev environment? Any way to overwrite a local Docker IP?

**Comment by hugorodgerbrown** [comment]
Hi @maltebeckmann - not sure why, but this message has only just come through. If you pull the master branch, you can run the project locally. You can run it as a django site (`python manage.py runserver`) and the middleware will be called. Let me know if you want to do this and I'll fire over config instructions.
