### ISSUE TITLE
1.3 upgrading to 2.0 results in 'WSGIRequest' object has no attribute 'geo_data'

### ISSUE THREAD

**Issue by iarp** [yunojuno/django-geoip2-extras#13]
Django 3.1 (waiting on 3 other packages to support 3.2).

I was on 1.3 and today i tried to update to 2.0 and the result is `'WSGIRequest' object has no attribute 'geo_data'`.

I do have `GEOIP_PATH = os.path.join(BASE_DIR, 'cache')` set in the project settings.py

I see that PR #12 was just merged but it seems to imply that `request.geo_data` should still exist?

**Comment by hugorodgerbrown** [comment]
It should indeed. I'll check when I get in to office. In the meantime, is there any output from runserver as it boots up?

**Comment by hugorodgerbrown** [comment]
Looking at code (on phone) the only reason I can see for not having it set is because the middleware isn't running, which suggests GeoIP2 or cache raised an error.

**Comment by hugorodgerbrown** [comment]
And it looks like I didn't add config instructions for cache to readme, so I suspect it's that. See demo/settings for an example.

**Comment by hugorodgerbrown** [comment]
ffs, I didn't add demo app either. My bad, will fix in next hour.

**Comment by hugorodgerbrown** [comment]
I have pushed a version to GH with an update to the README, and the `demo` app. There are no functional changes to this - so I'll hang back from publishing it.

**Comment by hugorodgerbrown** [comment]
I have pushed an update (2.0.1) with the demo app and an updated readme. I have also added some additional logging to help diagnose this. If you have the `geoip2_extras` logging handler set up you should see an `INFO` message on startup if the cache / geolite database are set up correctly:

```
System check identified no issues (0 silenced).
September 01, 2021 - 03:46:44
Django version 3.2.7, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
INFO GeoIP2 - successfully initialised local cache
INFO GeoIP2 - successfully initialised database reader
```

If you have the `django.request` logging handler set up you should see a `DEBUG` message if they can not be set up:

```
System check identified no issues (0 silenced).
September 01, 2021 - 03:44:59
Django version 3.2.7, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
DEBUG MiddlewareNotUsed('geoip2_extras.middleware.GeoIP2Middleware'): GeoError initialising GeoIP2: Could not load a database from /.../django-geoip2
```

**Comment by iarp** [comment]
It was the CACHES setting. I didn't have that and it won't load the middleware.
