### ISSUE TITLE
Object of type 'GeoData' is not JSON serializable

### ISSUE THREAD

**Issue by jaredfuelberth** [yunojuno/django-geoip2-extras#6]
After installing and getting geoip2 to work on the python console, this error occurs when running the actual Django project. In line 86 of middleware.py in the repo:
```
request.session[GeoIP2Middleware.SESSION_KEY] = request.geo_data = data
```
If you run ```json.dumps(data)```, you will get the error.

![image](https://user-images.githubusercontent.com/21299006/46434890-95bbf380-c71a-11e8-80ac-0cfe10048690.png)

**Comment by AndrewNappin-lumen** [comment]
Is this project going to get fixed?

**Comment by hugorodgerbrown** [comment]
Just cleaning this up. It's no longer relevant as the GeoData object is no longer serialized.
